ALTER TABLE classes ADD COLUMN IF NOT EXISTS start_date DATE;
ALTER TABLE classes ADD COLUMN IF NOT EXISTS end_date DATE;
ALTER TABLE classes ADD COLUMN IF NOT EXISTS exam_date TIMESTAMP;
ALTER TABLE classes ADD COLUMN IF NOT EXISTS exam_room VARCHAR(50);
ALTER TABLE classes ADD COLUMN IF NOT EXISTS exam_format VARCHAR(50);
ALTER TABLE classes ADD COLUMN IF NOT EXISTS exam_duration INTEGER;
